# Generated by Django 4.2.16 on 2025-07-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_alter_recipe_day_of_the_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(default=0, help_text='Cooking time in minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(blank=True, help_text='List of ingredients separated by commas or lines', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutritional_info',
            field=models.TextField(blank=True, help_text='Optional nutritional details', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prep_time',
            field=models.PositiveIntegerField(default=0, help_text='Preparation time in minutes'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_steps',
            field=models.TextField(blank=True, help_text='Step-by-step instructions for preparation', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveIntegerField(default=0, help_text='Number of servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_name',
            field=models.CharField(max_length=255),
        ),
    ]
